# Generated by Django 3.2.1 on 2021-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='number_of_seeds',
            field=models.IntegerField(default=1000, verbose_name='количество семян'),
        ),
    ]
