# Generated by Django 3.2.1 on 2021-05-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogApp', '0002_seed_number_of_seeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='purpose',
            field=models.CharField(default='Для выращивания в летний период в открытом грунте.', max_length=100, verbose_name='Предназначение'),
        ),
    ]
